swagger: '2.0'
info:
  version: 1.0.0
  title: Toast Authentication Metadata API
  description: 'The authentication API returns an authentication token that you can present

    when your integration client software uses other Toast APIs. For more

    information about authentication, see [the Toast Developer

    Guide](https://doc.toasttab.com/doc/devguide/authentication.html).

    '
  termsOfService: https://pos.toasttab.com/api-terms-of-use
  contact:
    name: Toast developer support
host: toast-api-server
basePath: /authentication/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
tags:
- name: Metadata
paths:
  /metadata:
    get:
      operationId: metadataGet
      summary: Toast Get Menu Last Modified Timestamp
      description: 'A lightweight endpoint that allows you to determine if a restaurant''s menu data has been updated. Toast support strongly recommends that you do not make a call to the `/menus` endpoint unless the date and time returned by the `/metadata` endpoint is more recent than the `lastUpdated` date and time. While this recommendation applies to all clients of the menus API, it is particularly important for clients that have limited bandwidth.

        '
      produces:
      - application/json
      parameters:
      - name: Toast-Restaurant-External-ID
        description: The identifier for the restaurant.
        in: header
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Metadata'
      security:
      - oauth2:
        - menus:read
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Metadata
definitions:
  Metadata:
    type: object
    description: 'Information about the last date and time that this restaurant''s menu data was updated.

      '
    properties:
      restaurantGuid:
        description: 'A unique identifier for this restaurant, assigned by the Toast POS system.

          '
        type: string
        format: uuid
        example: 5a401af8-d2e2-4090-8c45-9f87b8b6c4d1
      lastUpdated:
        description: 'The most recent date and time that this menu''s data was published. Use this value to determine if you need to refresh your menu data. The `lastUpdated` value uses the absolute timestamp format describe in the <a href="https://doc.toasttab.com/doc/devguide/api_dates_and_timestamps.html">Dates and timestamps</a> section of the Toast Developer Guide.

          '
        type: string
        example: string
externalDocs:
  description: Authentication developer guide
  url: https://doc.toasttab.com/doc/devguide/authentication.html
